### ISSUE TITLE
app not starting after successful deploy

### ISSUE THREAD

**Issue by ramanveerji** [WhatsGram/WhatsGram#1]
2021-05-18T21:02:41.947147+00:00 heroku[web.1]: Starting process with command `npm start`
2021-05-18T21:02:42.250959+00:00 app[worker.1]: internal/modules/cjs/loader.js:888
2021-05-18T21:02:42.250969+00:00 app[worker.1]:   throw err;
2021-05-18T21:02:42.250970+00:00 app[worker.1]:   ^
2021-05-18T21:02:42.250970+00:00 app[worker.1]: 
2021-05-18T21:02:42.250971+00:00 app[worker.1]: Error: Cannot find module '../modules/Carbon'
2021-05-18T21:02:42.250971+00:00 app[worker.1]: Require stack:
2021-05-18T21:02:42.250971+00:00 app[worker.1]: - /app/handlers/handleCreateMsg.js
2021-05-18T21:02:42.250972+00:00 app[worker.1]: - /app/index.js
2021-05-18T21:02:42.250973+00:00 app[worker.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
2021-05-18T21:02:42.250973+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
2021-05-18T21:02:42.250975+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:957:19)
2021-05-18T21:02:42.250975+00:00 app[worker.1]:     at require (internal/modules/cjs/helpers.js:88:18)
2021-05-18T21:02:42.250976+00:00 app[worker.1]:     at Object.<anonymous> (/app/handlers/handleCreateMsg.js:3:19)
2021-05-18T21:02:42.250976+00:00 app[worker.1]:     at Module._compile (internal/modules/cjs/loader.js:1068:30)
2021-05-18T21:02:42.250977+00:00 app[worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
2021-05-18T21:02:42.250977+00:00 app[worker.1]:     at Module.load (internal/modules/cjs/loader.js:933:32)
2021-05-18T21:02:42.250977+00:00 app[worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
2021-05-18T21:02:42.250978+00:00 app[worker.1]:     at Module.require (internal/modules/cjs/loader.js:957:19) {
2021-05-18T21:02:42.250978+00:00 app[worker.1]:   code: 'MODULE_NOT_FOUND',
2021-05-18T21:02:42.250979+00:00 app[worker.1]:   requireStack: [ '/app/handlers/handleCreateMsg.js', '/app/index.js' ]
2021-05-18T21:02:42.250979+00:00 app[worker.1]: }
2021-05-18T21:02:42.265224+00:00 app[worker.1]: [31m[nodemon] app crashed - waiting for file changes before starting...[39m
2021-05-18T21:02:44.872480+00:00 app[web.1]: 
2021-05-18T21:02:44.872509+00:00 app[web.1]: > WA@1.0.0 start /app
2021-05-18T21:02:44.872510+00:00 app[web.1]: > nodemon index.js
2021-05-18T21:02:44.872510+00:00 app[web.1]: 
2021-05-18T21:02:45.252588+00:00 app[web.1]: [33m[nodemon] 2.0.7[39m
2021-05-18T21:02:45.256404+00:00 app[web.1]: [33m[nodemon] to restart at any time, enter `rs`[39m
2021-05-18T21:02:45.256406+00:00 app[web.1]: [33m[nodemon] watching path(s): *.*[39m
2021-05-18T21:02:45.256406+00:00 app[web.1]: [33m[nodemon] watching extensions: js,mjs,json[39m
2021-05-18T21:02:45.256407+00:00 app[web.1]: [32m[nodemon] starting `node index.js`[39m
2021-05-18T21:02:46.135022+00:00 app[web.1]: internal/modules/cjs/loader.js:888
2021-05-18T21:02:46.135068+00:00 app[web.1]:   throw err;
2021-05-18T21:02:46.135068+00:00 app[web.1]:   ^
2021-05-18T21:02:46.135069+00:00 app[web.1]: 
2021-05-18T21:02:46.135070+00:00 app[web.1]: Error: Cannot find module '../modules/Carbon'
2021-05-18T21:02:46.135070+00:00 app[web.1]: Require stack:
2021-05-18T21:02:46.135070+00:00 app[web.1]: - /app/handlers/handleCreateMsg.js
2021-05-18T21:02:46.135071+00:00 app[web.1]: - /app/index.js
2021-05-18T21:02:46.135074+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
2021-05-18T21:02:46.135074+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:730:27)
2021-05-18T21:02:46.135075+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:957:19)
2021-05-18T21:02:46.135076+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:88:18)
2021-05-18T21:02:46.135076+00:00 app[web.1]:     at Object.<anonymous> (/app/handlers/handleCreateMsg.js:3:19)
2021-05-18T21:02:46.135077+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1068:30)
2021-05-18T21:02:46.135077+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
2021-05-18T21:02:46.135078+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:933:32)
2021-05-18T21:02:46.135078+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:774:14)
2021-05-18T21:02:46.135078+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:957:19) {
2021-05-18T21:02:46.135079+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',
2021-05-18T21:02:46.135079+00:00 app[web.1]:   requireStack: [ '/app/handlers/handleCreateMsg.js', '/app/index.js' ]
2021-05-18T21:02:46.135080+00:00 app[web.1]: }
2021-05-18T21:02:46.143040+00:00 app[web.1]: [31m[nodemon] app crashed - waiting for file changes before starting...[39m
2021-05-18T21:03:42.561064+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2021-05-18T21:03:42.609112+00:00 heroku[web.1]: Stopping process with SIGKILL
2021-05-18T21:03:42.679809+00:00 heroku[web.1]: Process exited with status 137
2021-05-18T21:03:42.748865+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by AffanTheBest** [comment]
Error resolved, closing now!
