### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [WhatsGram/WhatsGram#8]
/app/node_modules/deta/dist/index.js:829
2022-07-25T10:25:18.561240+00:00 app[worker.1]:         throw new Error('Project key is not defined');
2022-07-25T10:25:18.561241+00:00 app[worker.1]:         ^
2022-07-25T10:25:18.561241+00:00 app[worker.1]: 
2022-07-25T10:25:18.561242+00:00 app[worker.1]: Error: Project key is not defined
2022-07-25T10:25:18.561242+00:00 app[worker.1]:     at Deta (/app/node_modules/deta/dist/index.js:829:15)
2022-07-25T10:25:18.561242+00:00 app[worker.1]:     at Object.<anonymous> (/app/handlers/handleSession.js:8:14)
2022-07-25T10:25:18.561243+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1105:14)
2022-07-25T10:25:18.561243+00:00 app[worker.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
2022-07-25T10:25:18.561243+00:00 app[worker.1]:     at Module.load (node:internal/modules/cjs/loader:981:32)
2022-07-25T10:25:18.561244+00:00 app[worker.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
2022-07-25T10:25:18.561244+00:00 app[worker.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19)
2022-07-25T10:25:18.561245+00:00 app[worker.1]:     at require (node:internal/modules/cjs/helpers:102:18)
2022-07-25T10:25:18.561245+00:00 app[worker.1]:     at Object.<anonymous> (/app/index.js:12:39)
2022-07-25T10:25:18.561245+00:00 app[worker.1]:     at Module._compile (node:internal/modules/cjs/loader:1105:14)
2022-07-25T10:25:18.780974+00:00 heroku[worker.1]: State changed from up to crashed
2022-07-25T10:25:18.691821+00:00 heroku[worker.1]: Process exited with status 1

**Comment by siddiquiaffan** [comment]
Get API key from https://web.deta.sh/ and add it to environment variables as **DETA_PROJECT_KEY**

**Comment by ghost** [comment]
/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
2022-07-26T10:55:29.549722+00:00 app[worker.1]:             throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
2022-07-26T10:55:29.549723+00:00 app[worker.1]:                   ^
2022-07-26T10:55:29.549724+00:00 app[worker.1]: 
2022-07-26T10:55:29.549724+00:00 app[worker.1]: Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'notSpam')
2022-07-26T10:55:29.549725+00:00 app[worker.1]:     at y.isTrusted (https://web.whatsapp.com/bootstrap_qr.f74b98c729dd38392a5f.js:75:599370)
2022-07-26T10:55:29.549725+00:00 app[worker.1]:     at y.downloadMedia (https://web.whatsapp.com/bootstrap_qr.f74b98c729dd38392a5f.js:75:600915)
2022-07-26T10:55:29.549726+00:00 app[worker.1]:     at __puppeteer_evaluation_script__:6:27
2022-07-26T10:55:29.549726+00:00 app[worker.1]:     at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
2022-07-26T10:55:29.549726+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-07-26T10:55:29.549727+00:00 app[worker.1]:     at async ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
2022-07-26T10:55:29.549727+00:00 app[worker.1]:     at async Message.downloadMedia (/app/node_modules/whatsapp-web.js/src/structures/Message.js:384:24)
2022-07-26T10:55:29.549727+00:00 app[worker.1]:     at async handleMessage (/app/handlers/handleMessage.js:52:9)
2022-07-26T10:55:29.743168+00:00 heroku[worker.1]: Process exited with status 1
2022-07-26T10:55:29.819491+00:00 heroku[worker.1]: State changed from up to crashed

**Comment by ghost** [comment]
fixed
