### ISSUE TITLE
Error: Project key is not defined

### ISSUE THREAD

**Issue by N30Z3N** [WhatsGram/WhatsGram#9]
2022-07-27T18:30:08.408223+00:00 app[web.1]: 

2022-07-27T18:30:08.408238+00:00 app[web.1]: > WhatsGram@1.0.0 start

2022-07-27T18:30:08.408239+00:00 app[web.1]: > node index.js

2022-07-27T18:30:08.408239+00:00 app[web.1]: 

2022-07-27T18:30:09.136065+00:00 heroku[web.1]: Process exited with status 1

2022-07-27T18:30:08.987756+00:00 app[web.1]: /app/node_modules/deta/dist/index.js:829

2022-07-27T18:30:08.987777+00:00 app[web.1]:         throw new Error('Project key is not defined');

2022-07-27T18:30:08.987778+00:00 app[web.1]:         ^

2022-07-27T18:30:08.987778+00:00 app[web.1]: 

2022-07-27T18:30:08.987778+00:00 app[web.1]: Error: Project key is not defined

2022-07-27T18:30:08.987778+00:00 app[web.1]:     at Deta (/app/node_modules/deta/dist/index.js:829:15)

2022-07-27T18:30:08.987779+00:00 app[web.1]:     at Object.<anonymous> (/app/handlers/handleSession.js:8:14)

2022-07-27T18:30:08.987779+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1105:14)

2022-07-27T18:30:08.987780+00:00 app[web.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

2022-07-27T18:30:08.987780+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:981:32)

2022-07-27T18:30:08.987780+00:00 app[web.1]:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)

2022-07-27T18:30:08.987781+00:00 app[web.1]:     at Module.require (node:internal/modules/cjs/loader:1005:19)

2022-07-27T18:30:08.987781+00:00 app[web.1]:     at require (node:internal/modules/cjs/helpers:102:18)

2022-07-27T18:30:08.987781+00:00 app[web.1]:     at Object.<anonymous> (/app/index.js:12:39)

2022-07-27T18:30:08.987781+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1105:14)

2022-07-27T18:30:09.247133+00:00 heroku[web.1]: State changed from starting to crashed

**Comment by siddiquiaffan** [comment]
Have look at issue #8
